# Reproduce the table with photometric uncertainties on the Gaia science performance pages

The code below shows how to reproduce the numbers in the [table of photometric uncertainties](https://www.cosmos.esa.int/web/gaia/science-performance#photometric%20performance) on the Gaia science performance web pages. This notebook also serves as a test to verify that the numbers on the science performance pages are correctly reproduced.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from pygaia.errors.photometric import magnitude_uncertainty as magunc
from pygaia.photometry.transformations import gbrminv_from_vminic

## Calculating the uncertainties at fixed $G$ for different spectral types

The code below uses the transformations from the Johnson-Cousins to the Gaia photometric systems to assign the correct values of $G_\mathrm{BP}$ and $G_\mathrm{RP}$, given $G$, for stars of different spectral types (B1V, G2V, M6V).

In [2]:
gmags = np.arange(13,21)
gbpmags = {}
grpmags = {}
spt_vminic = {"B1V":-0.22, "G2V":0.75, "M6V":3.85}

for spt in spt_vminic.keys():
    gminv, bpminv, rpminv, _ = gbrminv_from_vminic(spt_vminic[spt])
    gbpmags[spt] = gmags + bpminv - gminv
    grpmags[spt] = gmags + rpminv - gminv

dfs = {}
for spt in spt_vminic.keys():
    dfs[spt] = pd.DataFrame({"G":gmags})
    for release in ["dr3", "dr4", "dr5"]:
        dfs[spt][f"sigG_{release.upper()}"] = magunc("g", gmags, release=release)
    for release in ["dr3", "dr4", "dr5"]:
        valid = gbpmags[spt] <= 21.0
        uncs = np.zeros(gmags.size)
        uncs[valid] = magunc("bp", gbpmags[spt][valid], release=release)
        uncs[np.logical_not(valid)] = np.nan
        dfs[spt][f"sigBP_{release.upper()}"] = uncs
    for release in ["dr3", "dr4", "dr5"]:
        valid = grpmags[spt] <= 21.0
        uncs = np.zeros(gmags.size)
        uncs[valid] = magunc("rp", grpmags[spt][valid], release=release)
        uncs[np.logical_not(valid)] = np.nan
        dfs[spt][f"sigRP_{release.upper()}"] = uncs

In [3]:
spt="B1V"
dfs[spt].style.format("{:.1f}").hide(axis="index").set_caption(spt)

In [4]:
spt="G2V"
dfs[spt].style.format("{:.1f}").hide(axis="index").set_caption(spt)

In [5]:
spt="M6V"
dfs[spt].style.format("{:.1f}", na_rep="-").hide(axis="index").set_caption(spt)